---

- name: Set up filebeat config
  become: true
  become_user: root

  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Enable and start filebeat service
  become: true
  become_user: root

  systemd:
    name: filebeat
    state: restarted
    daemon_reload: true
    enabled: true
