---

- name: Set up filebeat config
  become: true
  become_user: root

  template:
    src: templates/filebeat_{{ app_name }}.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600

- name: Enable filebeat service
  become: true
  become_user: root

  systemd:
    name: filebeat
    state: restarted
    daemon_reload: true
    enabled: true
