app_debug: True
secret_key: zgt(m7!mg^!ln011u3rvgg^9a1rv+ebff&!*t@ntf@k-iipm^9
env: dev
postgres_db_name: mtdj_database
postgresql_db_password: scyy#n9f!hn=)3k5zzd*u76)n=n)%-)c9t%^%o3=9n-)qfgeck
postgresql_db_user: postgres
logging_dir: /var/log/mtdj

requirements_file: "{{ repository_path }}/requirements/dev.txt"

startup_commands: |
  . ~/mtdj_env/bin/activate
  cd ~/moodytunes/
  export MTDJ_ENV_FILE="{{ repository_path }}/.env"
