---

- name: Update repositories cache and install Logstash

  apt:
    name: logstash
    update_cache: yes

- name: Configure Beats configuration file

  template:
    src: beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Syslog Filter

  template:
    src: syslog-filter.conf.j2
    dest: /etc/logstash/conf.d/10-syslog-filter.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Elasticsearch output file

  template:
    src: elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    owner: root
    group: root
    mode: 0644

- name: Start Logstash service

  systemd:
    name: logstash
    state: started
    daemon_reload: yes

- name: Enable Logstash service

  systemd:
    name: logstash
    enabled: yes
