---

- name: Add beats configuration file

  template:
    src: beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
    owner: root
    group: root
    mode: 0644

- name: Configure application filter

  template:
    src: application-filter.conf.j2
    dest: /etc/logstash/conf.d/12-application-filter.conf
    owner: root
    group: root
    mode: 0644

- name: Configure gunicorn filter

  template:
    src: gunicorn-filter.conf.j2
    dest: /etc/logstash/conf.d/13-gunicorn-filter.conf
    owner: root
    group: root
    mode: 0644

- name: Configure nginx filter

  template:
    src: nginx-filter.conf.j2
    dest: /etc/logstash/conf.d/14-nginx-filter.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Elasticsearch output file

  template:
    src: elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Logstash Java config
  template:
    src: jvm.options
    dest: /etc/logstash/jvm.options
    owner: root
    group: root
    mode: 0644

- name: Enable and start Logstash service

  systemd:
    name: logstash
    state: restarted
    daemon_reload: true
    enabled: true
