- name: Ensure nginx is running
  become_user: root
  no_log: true

  service:
    name: nginx
    state: started

- name: Create nginx config file
  become_user: root

  template:
    src: templates/nginx
    dest: /etc/nginx/conf.d/{{ app_name }}.conf

  notify: restart nginx
