---

- name: Create nginx config file
  become: true
  become_user: root

  template:
    src: templates/conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf

  notify: restart nginx

- name: Create nginx application server conf
  become: true
  become_user: root

  template:
    src: templates/{{ app_name }}/nginx.j2
    dest: /etc/nginx/sites-available/{{ app_hostname }}

  notify: restart nginx

- name: Create symlink to application server conf
  become: true
  become_user: root

  file:
    src: /etc/nginx/sites-available/{{ app_hostname }}
    dest: /etc/nginx/sites-enabled/default
    state: link

  notify: restart nginx
