- name: Create gunicorn user
  become_user: root

  user:
    name: "{{ gunicorn_user }}"
    groups: "{{ system_group }}"
    create_home: no

- name: Create gunicorn logging directory
  become_user: root

  file:
    path: "{{ gunicorn_logging_directory }}"
    owner: "{{ gunicorn_user }}"
    state: directory

- name: Create gunicorn.d directory
  become_user: root

  file:
    path: /etc/gunicorn.d
    state: directory

- name: Create gunicorn config file
  become_user: root

  template:
    src: templates/gunicorn.py
    dest: /etc/gunicorn.d/gunicorn.py

- name: Create gunicorn systemd file
  become_user: root

  template:
    src: templates/gunicorn.service
    dest: /etc/systemd/system/gunicorn.service

- name: Start gunicorn daemon on non local environments
  become_user: root

  service:
    name: gunicorn
    state: restarted

  when: playbook_env != 'local'

  notify: restart nginx
