---

- name: Create gunicorn.d directory
  become: true
  become_user: root

  file:
    path: /etc/gunicorn.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create gunicorn config file
  become: true
  become_user: root

  template:
    src: templates/gunicorn.py
    dest: /etc/gunicorn.d/gunicorn.py
    owner: root
    group: root
    mode: 0644

- name: Create gunicorn systemd file
  become: true
  become_user: root

  template:
    src: templates/gunicorn.service
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: 0644
