---

- name: Create gunicorn.d directory
  become: true
  become_user: root

  file:
    path: /etc/gunicorn.d
    state: directory

- name: Create gunicorn config file
  become: true
  become_user: root

  template:
    src: templates/gunicorn.py
    dest: /etc/gunicorn.d/gunicorn.py

- name: Create gunicorn systemd file
  become: true
  become_user: root

  template:
    src: templates/gunicorn.service
    dest: /etc/systemd/system/gunicorn.service
