---

- name: Provision ELK Hosts
  hosts: moodytunes-elk
  become: true
  become_user: root

  roles:
    - apt_keys
    - apt
    - elasticsearch
    - kibana
    - openssl
    - ufw
    - nginx
    - logstash
