---

- name: Configure Application
  hosts: all
  become: true
  become_user: root

  roles:
    - apt-keys
    - apt
    - elasticsearch
    - kibana
    - openssl
    - ufw
    - nginx
    - logstash
