---

- name: Provision Moodytunes Hosts
  hosts: moodytunes
  become: true
  become_user: "{{ provisioning_user }}"

  roles:
    - apt_keys
    - apt
    - system
    - logrotate
    - users
    - ufw
    - openssl
    - sshd
    - nginx
    - postgres
    - git
    - python
    - env
    - gunicorn
    - celery
    - node
    - django
    - filebeat
    - services
