---

- name: Configure Application
  hosts: all
  become: true
  become_user: "{{ default_user }}"

  roles:
    - apt
    - system
    - logrotate
    - users
    - ufw
    - openssl
    - nginx
    - git
    - env
    - postgres
    - gunicorn
    - celery
    - node
    - django
    - services
