---

- name: Set up nginx reverse proxy for Kibana

  template:
    src: kibana.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Enable and start nginx service

  systemd:
    name: nginx
    enabled: true
    state: restarted
    daemon_reload: true
