---

- name: Update repositories cache and install Nginx
  become: true
  become_user: root

  apt:
    name: nginx
    update_cache: yes

- name: Create nginx directory structure
  become: true
  become_user: root

  file:
    path: /etc/nginx/conf.d/
    state: directory
    mode: 0755

- name: Setup Nginx reverse proxy for kibana
  become: true
  become_user: root

  template:
    src: kibana.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Enable Nginx service
  become: true
  become_user: root

  systemd:
    name: nginx
    enabled: yes

- name: Start Nginx service
  become: true
  become_user: root

  systemd:
    name: nginx
    state: started
    daemon_reload: yes

- name: Install Python Pexpect
  become: true
  become_user: root

  apt:
    name: python3-pexpect
    update_cache: yes

- name: Add create kibana admin user script
  become: true
  become_user: root

  template:
    src: kibanaAdmin.j2
    dest: /tmp/createUser
    owner: root
    group: root
    mode: 0744

- name: Create Kibana admin user
  become: true
  become_user: root

  expect:
    command: /tmp/createUser
    responses:
      'Password:' : "{{ kibana_password }}"

- name: Restart Nginx service
  become: true
  become_user: root

  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes
