---

- name: Install packages
  become: yes
  become_user: root

  apt:
    pkg: "{{ site_packages }}"
    state: latest
    update_cache: true

- name: Update system packages
  become: yes
  become_user: root

  apt:
    upgrade: dist
