---

- name: Install packages
  become: true
  become_user: root

  apt:
    pkg: "{{ packages }}"
    state: latest  # noqa: 403
    update_cache: true

- name: Update system packages
  become: true
  become_user: root

  apt:
    upgrade: dist
