base_commands:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - python manage.py compress --force

django_commands: "{{ base_commands }} + {{ django_commands_extend | default([]) }}"
