#!/bin/bash

_systemctl_complete()
{
  local cur prev

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=( $(compgen -W "daemon-reload restart start stop status" -- $cur) )
  elif [ $COMP_CWORD -eq 2 ]; then
    COMPREPLY=( $(compgen -W "celery celery_beat nginx gunicorn smtp" -- $cur) )
  fi

  return 0
}

complete -F _systemctl_complete systemctl
