---

- name: Configure application logfiles logrotate config
  become: true
  become_user: root

  template:
    src: templates/application.conf
    dest: /etc/logrotate.d/application
    owner: root
    group: root
    mode: 0644
