---

- name: Install kibana
  become: true
  become_user: root

  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Enable Kibana service
  become: true
  become_user: root

  systemd:
    name: kibana
    enabled: yes
    daemon_reload: yes

- name: Start Kibana service
  become: true
  become_user: root

  systemd:
    name: kibana
    state: started

