---

- name: Install kibana

  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Enable Kibana service

  systemd:
    name: kibana
    enabled: yes
    daemon_reload: yes

- name: Start Kibana service

  systemd:
    name: kibana
    state: started

