---

- name: Create system group
  become: true
  become_user: root

  group:
    name: "{{ system_group }}"
    system: true

- name: Add provisioning user to system group
  become: true
  become_user: root

  user:
    name: "{{ provisioning_user }}"
    groups: "{{ system_group }}"
    append: true

- name: Create celery user
  become: true
  become_user: root

  user:
    name: "{{ celery_user }}"
    groups: "{{ system_group }}"
    create_home: false

- name: Create gunicorn user
  become: true
  become_user: root

  user:
    name: "{{ gunicorn_user }}"
    groups: "{{ system_group }}"
    create_home: false

- name: Create application parent directory
  become: true
  become_user: root

  file:
    path: "{{ application_directory }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: u=rwx,g=rwx

- name: Configure logging path
  become: true
  become_user: root

  file:
    path: "{{ logging_dir }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx,g+s

- name: Configure data directory path
  become: true
  become_user: root

  file:
    path: "{{ data_path }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: u=rwx,g=rwx,g+s

- name: Configure database backups directory path
  become: true
  become_user: root

  file:
    path: "{{ database_backup_path }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: u=rwx,g=rwx,g+s

- name: Configure image file upload directory path
  become: true
  become_user: root

  file:
    path: "{{ image_file_upload_path }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: u=rwx,g=rwx,g+s

- name: Add application startup script

  template:
    src: bash_templates/application-startup
    dest: "{{ home_directory }}/.application-startup"

- name: Add startup commands to profile

  blockinfile:
    path: "{{ home_directory }}/.profile"
    block: "{{ startup_commands }}"
