- name: Create system group
  become_user: root

  group:
    name: "{{ system_group }}"
    system: yes

- name: Create celery user
  become_user: root

  user:
    name: "{{ celery_user }}"
    groups: "{{ system_group }}"
    create_home: no

- name: Create gunicorn user
  become_user: root

  user:
    name: "{{ gunicorn_user }}"
    groups: "{{ system_group }}"
    create_home: no

- name: Configure logging path
  become_user: root

  file:
    path: "{{ logging_dir }}"
    owner: "{{ default_user }}"
    group: "{{ system_group }}"
    state: directory
    mode: 0770

- name: Create application log file
  become_user: root

  file:
    path: "{{ logging_dir }}/application.log"
    owner: "{{ default_user }}"
    group: "{{ system_group }}"
    state: touch
    mode: 0660

- name: Create application error file
  become_user: root

  file:
    path: "{{ logging_dir }}/error.log"
    owner: "{{ default_user }}"
    group: "{{ system_group }}"
    state: touch
    mode: 0660

- name: Add application startup script

  template:
    src: templates/application-startup
    dest: "{{ home_directory }}/.application-startup"

- name: Add systemd auto complete source file
  
  copy:
    src: templates/systemctl-complete
    dest: "{{ home_directory }}/.systemctl-complete.bash"

- name: Add startup commands to profile

  blockinfile:
    path: "{{ home_directory }}/.profile"
    block: "{{ startup_commands }}"
