---

- name: Add Elastisearch apt repo key
  become: true
  become_user: root

  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elastisearch apt repo
  become: true
  become_user: root

  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x.list
    update_cache: yes

- name: Install java
  become: true
  become_user: root

  apt:
    name: openjdk-8-jre
    state: present
    update_cache: yes

- name: Install Elastisearch
  become: true
  become_user: root

  apt:
    pkg: elasticsearch
    state: present
    update_cache: true

- name: Set Elastisearch network host to local
  become: true
  become_user: root

  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "^network.host"
    line: "network.host: localhost"

- name: Start Elastisearch
  become: true
  become_user: root

  service:
    name: elasticsearch
    state: restarted
