---

- name: Add Elastisearch apt repo key

  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elastisearch apt repo

  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x.list
    update_cache: true

- name: Install Elastisearch

  apt:
    pkg: elasticsearch
    state: present
    update_cache: true

- name: Set Elastisearch network host to local

  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "^network.host"
    line: "network.host: localhost"

- name: Start Elastisearch

  service:
    name: elasticsearch
    state: restarted
