---

- name: Create celery PID directory
  become: true
  become_user: root

  file:
    path: "{{ celery_pid_directory }}"
    state: directory
    owner: "{{ celery_user }}"

- name: Create celery systemd file
  become: true
  become_user: root

  template:
    src: templates/celery.service
    dest: /etc/systemd/system/celery.service

- name: Create celery-beat systemd file
  become: true
  become_user: root

  template:
    src: templates/celery_beat.service
    dest: /etc/systemd/system/celery_beat.service
