---

- name: Add tmpfiles.d config for celery PID directory
  become: true
  become_user: root

  lineinfile:
    path: /usr/lib/tmpfiles.d/celery.conf
    create: yes
    line: d {{ celery_pid_directory }} 755 celery root - -

- name: Create celery systemd file
  become: true
  become_user: root

  template:
    src: templates/celery.service
    dest: /etc/systemd/system/celery.service

- name: Create celery-beat systemd file
  become: true
  become_user: root

  template:
    src: templates/celery_beat.service
    dest: /etc/systemd/system/celery_beat.service
