---

- name: Enable ufw firewall
  become: true
  become_user: root

  ufw:
    state: enabled

- name: Enable OpenSSH
  become: true
  become_user: root

  ufw:
    name: OpenSSH
    rule: allow
    state: enabled

- name: Enable nginx
  become: true
  become_user: root

  ufw:
    name: Nginx Full
    rule: allow
    state: enabled

- name: Enable postgres on local
  become: true
  become_user: root

  ufw:
    rule: allow
    port: 5432
    proto: tcp
    state: enabled

  when: playbook_env == 'local'
