---

- name: Check if Github is in known_hosts file

  command: ssh-keygen -f {{ known_hosts_file }} -F github.com

  register: github_known_host_result
  ignore_errors: true
  no_log: true
  changed_when: github_known_host_result.failed

- name: Add Github public key to known_hosts if it is not present

  lineinfile:
    path: "{{ known_hosts_file }}"
    create: true
    state: present
    regexp: "^github\\.com"
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    owner: "{{ provisioning_user }}"
    group: "{{ provisioning_user }}"
    mode: 0664

  when: github_known_host_result.failed

- name: Clone repository

  git:
    dest: "{{ repository_path }}"
    repo: "{{ repository_url }}"
    version: "{{ git_version }}"
    ssh_opts: -o AddressFamily=inet
