---

- name: Check if Github is in known_hosts file

  command: ssh-keygen -f {{ known_hosts_file }} -F github.com

  register: github_known_host_result
  ignore_errors: true
  no_log: true
  changed_when: github_known_host_result.failed

- name: Add Github public key to known_hosts if it is not present

  shell: ssh-keyscan -H -T 10 github.com >> {{ known_hosts_file }}

  when: github_known_host_result.failed

- name: Clone repository

  git:
    dest: "{{ repository_path }}"
    repo: "{{ repository_url }}"
    version: "{{ git_version }}"
