- name: Create users group
  become_user: root

  group:
    name: "{{ user_group }}"

- name: Create defined users
  become_user: root

  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"

  with_items:
    - "{{ users }}"

- name: Add user SSH keys
  become_user: root

  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"

  with_items:
    - "{{ users }}"
