---

- name: Create staff group on moodytunes hosts
  become: true
  become_user: root

  group:
    name: "{{ staff_group }}"

  when: app_name == 'mtdj'

- name: Create defined users
  become: true
  become_user: root

  user:
    name: "{{ item.name }}"
    password: ""  # Set using `passwd` on first login
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    home: "{{ item.home }}"
    update_password: on_create

  with_items:
    - "{{ users }}"

- name: Add user SSH keys
  become: true
  become_user: root

  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"

  with_items:
    - "{{ users }}"

- name: Add application startup script to user home directories on moodytunes hosts
  become: true
  become_user: root

  template:
    src: bash_templates/application-startup
    dest: "{{ item.home }}/.application-startup"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644

  with_items:
    - "{{ users }}"

  when: app_name == 'mtdj'

- name: Add startup commands to profile on moodytunes hosts
  become: true
  become_user: root

  blockinfile:
    path: "{{ item.home }}/.profile"
    block: "{{ startup_commands }}"

  with_items:
    - "{{ users }}"

  when: app_name == 'mtdj'
