- name: Create users group
  become_user: root

  group:
    name: "{{ user_group }}"

- name: Create defined users
  become_user: root

  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"

  with_items:
    - "{{ users }}"
