---

- name: Setup Django project
  shell: . {{ home_directory }}/.application-startup && {{ item }}  # noqa: 301

  with_items:
    - "{{ django_commands }}"

- name: Clear compiled python files
  shell: cd {{ repository_path }} && find . -name "__pycache__" -delete  # noqa: 301
