---

- name: Setup Django project
  shell: . {{ home_directory }}/.application-startup && {{ item.command }}  # noqa: 301
  register: result

  with_items:
    - "{{ django_commands }}"

  changed_when: "item.ignore not in result.stdout"


- name: Clear compiled python files
  become: true
  become_user: root

  shell: find {{ repository_path }} -type d -name "__pycache__" -exec rm -rf {} +   # noqa: 301
