---

- name: Setup Django project
  shell: . {{ home_directory }}/.application-startup && {{ item }}

  with_items:
    - "{{ django_commands }}"

- name: Clear compiled python files
  shell: cd {{ repository_path }} && find . -name *.pyc -delete
