- name: Setup Django project
  shell: . {{ home_directory }}/.profile && {{ item }}
  with_items:
    - python manage.py migrate
    - python manage.py loaddata apps/tunes/fixtures/Initial_Songs.json
    - python manage.py collectstatic --noinput
    - python manage.py clean_pyc
  args:
    executable: /bin/bash
