---

- name: Setup Django project
  shell: . {{ home_directory }}/.application-startup && {{ item }}  # noqa: 301

  with_items:
    - "{{ django_commands }}"

- name: Clear compiled python files
  become: true
  become_user: root

  shell: find {{ repository_path }} -type d -name "__pycache__" -exec rm -rf {} +   # noqa: 301
