---

- name: Set up Elasticsearch config

  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Start Elasticsearch

  service:
    name: elasticsearch
    state: restarted

- name: Enable Elasticsearch service

  systemd:
    name: elasticsearch
    enabled: true
    daemon_reload: true
