---

- name: Set up Elasticsearch config

  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Enable and start Elasticsearch service

  systemd:
    name: elasticsearch
    state: restarted
    enabled: true
    daemon_reload: true
