---

- name: Set up Elasticsearch config

  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: Set up Elasticsearch Java config

  template:
    src: templates/meminfo.options
    dest: /etc/elasticsearch/jvm.options.d
    owner: root
    group: elasticsearch
    mode: 0660

- name: Enable and start Elasticsearch service

  systemd:
    name: elasticsearch
    state: restarted
    enabled: true
    daemon_reload: true
