---

- name: Ensure database is created
  become: true
  become_user: postgres

  postgresql_db:
    name: "{{ postgres_db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

  notify: restart postgresql

- name: Create application database user to access the database
  become: true
  become_user: postgres

  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    priv: ALL
    state: present

  notify: restart postgresql

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres

  postgresql_user:
    name: "{{ postgresql_db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present

  notify: restart postgresql

- name: Grant user permission to create test database on local
  become: true
  become_user: postgres

  postgresql_user:
    name: "{{ postgresql_db_user }}"
    role_attr_flags: CREATEDB
    state: present

  when: playbook_env == 'local'
  notify: restart postgresql

- name: Allow connections from all hosts on local
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    regexp: '^#listen_addresses'
    line: listen_addresses = '*'

  when: playbook_env == 'local'
  notify: restart postgresql

- name: Allow access to all databases on local
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: host all all all md5

  when: playbook_env == 'local'
  notify: restart postgresql
