- name: Ensure database is created
  become_user: postgres
  
  postgresql_db:
    name: "{{ postgres_db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

  notify: restart postgresql

- name: Create application user has access to the database
  become_user: postgres
  
  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    priv: ALL
    state: present

  notify: restart postgresql

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present

  notify: restart postgresql
