---

- name: Create database on db hosts and local mtdj

  include_tasks: create_db.yml
  when: app_name == 'db' or (app_name == 'mtdj' and playbook_env == 'local')

- name: Configure local database

  include_tasks: setup_local_db.yml
  when: playbook_env == 'local' and app_name == 'mtdj'

- name: Configure database host

  include_tasks: setup_db_host.yml
  when: app_name == 'db'
