---

- name: Create postgresql.conf file
  become: true
  become_user: root

  template:
    src: templates/postgresql.conf.j2
    dest: /etc/postgresql/10/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644

  notify: restart postgresql

- name: Create pg_hba.conf file
  become: true
  become_user: root

  template:
    src: templates/{{ playbook_env }}_pg_hba.conf.j2
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640

  notify: restart postgresql

- name: Create personal users on prod hosts
  become: true
  become_user: root

  user:
    name: "{{ item.name }}"
    password: ""  # Set using `passwd` on first login
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    home: "{{ item.home }}"
    update_password: on_create

  with_items:
    - "{{ users }}"

  when: playbook_env == 'prod'


- name: Add user SSH keys on prod hosts
  become: true
  become_user: root

  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"

  with_items:
    - "{{ users }}"

  when: playbook_env == 'prod'
