---

- name: Listen on public IP address for database hosts
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    line: listen_addresses = '{{ postgresql_ip_address }}, 127.0.0.1'

  notify: restart postgresql

- name: Allow database access for mtdj server on database hosts
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: host {{ postgres_db_name }} {{ postgresql_db_user }} {{ moodytunes_hostname }} md5

  notify: restart postgresql
