---

- name: Listen on all addresses for local mtdj databases
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/postgresql.conf
    line: listen_addresses = '*'

  notify: restart postgresql

- name: Allow access to all databases on local mtdj databases
  become: true
  become_user: root

  lineinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    line: host all all all md5

  notify: restart postgresql
