---

- name: Create postgresql.conf file
  become: true
  become_user: root

  template:
    src: templates/postgresql.conf.j2
    dest: /etc/postgresql/10/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644

  notify: restart postgresql

- name: Create pg_hba.conf file
  become: true
  become_user: root

  template:
    src: templates/pg_hba.conf.j2
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640

  notify: restart postgresql
