---

- name: Reload systemd units
  become: true
  become_user: root

  systemd:
    daemon-reload: true

- name: Start gunicorn service
  become: true
  become_user: root

  systemd:
    name: gunicorn
    state: restarted
    enabled: true

  notify: restart nginx

- name: Start celery service
  become: true
  become_user: root

  systemd:
    name: celery
    state: restarted
    enabled: true

- name: Start celery_beat service
  become: true
  become_user: root

  systemd:
    name: celery_beat
    state: restarted
    enabled: true

- name: Ensure all systemd unit have started successfully
  become: true
  become_user: root

  command: systemctl list-units --all --failed  # noqa 303
  register: result

  failed_when: "'0 loaded units listed.' not in result.stdout"
  changed_when: False
