---

- name: Reload systemd units
  become: true
  become_user: root

  systemd:
    daemon-reload: true

- name: Start services
  become: true
  become_user: root

  systemd:
    name: "{{ item.name }}"
    state: restarted
    enabled: true

  with_items:
    - "{{ services }}"

- name: Ensure all systemd unit have started successfully
  become: true
  become_user: root

  command: systemctl list-units --all --failed  # noqa 303
  register: result

  failed_when: "'0 loaded units listed.' not in result.stdout"
  changed_when: False
