---

- name: Reload systemd units
  become: true
  become_user: root

  systemd:
    daemon-reload: true

- name: Start gunicorn service
  become: true
  become_user: root

  service:
    name: gunicorn
    state: restarted

  notify: restart nginx

- name: Start celery service
  become: true
  become_user: root

  service:
    name: celery
    state: restarted

- name: Start celery_beat service
  become: true
  become_user: root

  service:
    name: celery_beat
    state: restarted
