---

- name: Create environment variables list
  become: true
  become_user: root

  template:
    src: templates/env
    dest: "{{ env_file_path }}"
    owner: "{{ provisioning_user }}"
    group: "{{ system_group }}"
    mode: 0440
