- name: Create virtual environment

  command: virtualenv {{ virtualenv_dir }} --python={{ python_path }}

- name: Install requirements

  pip:
    virtualenv: "{{ virtualenv_dir }}"
    requirements: "{{ requirements_file }}"

- name: Create environment variables list

  template:
    src: templates/env
    dest: "{{ repository_path }}/.env"
