- name: Create virtual environment
  command: virtualenv {{ virtualenv_dir }} --python={{ python_path }}

- name: Install requirements
  pip:
    virtualenv: "{{ virtualenv_dir }}"
    requirements: "{{ requirements_file }}"
