---

name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          grep yamllint requirements.txt | xargs pip install
      - name: Run yamllint
        run: yamllint -c .yaml_lint_config .

  ansible-lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          grep ansible-lint requirements.txt | xargs pip install
      - name: Run ansible-lint
        run: ansible-lint site.yml elk.yml

  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
